### ISSUE TITLE
Vytvoření endpointu pro vložení úkolu

### ISSUE THREAD

**Issue by Michus001** [CLV-Java-Akademie-2021/hr-system#10]
Metoda: POST
Adresa: http://localhost:8080/api/task

Controller pošle do servisní vrstvy data (id společnosti, název CZ, název EN) ze vstupu do servisní vrstvy a zde je jen zaloguje.

**Comment by AdVy01** [comment]
https://github.com/AdVy01/hr-system
Bohužel se mi nepodařilo commitnout do tohoto projektu.
