### ISSUE TITLE
Vytvoření endpointu pro vložení nové společnosti

### ISSUE THREAD

**Issue by Michus001** [CLV-Java-Akademie-2021/hr-system#8]
Metoda: POST
Adresa: http://localhost:8080/api/company

Controller pošle do servisní vrstvy data (název, adresa) ze vstupu do servisní vrstvy a zde je jen zaloguje.

**Comment by Ondrej-Martinek** [comment]
https://github.com/CLV-Java-Akademie-2021/hr-system/tree/OndraM
